name: Hourly YouTube News Bot

on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час
  workflow_dispatch:  # Запуск вручную

jobs:
  run-news-bot:
    runs-on: ubuntu-latest  # Используем образ Ubuntu для выполнения

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Update package list
        run: sudo apt-get update  # Обновляем список пакетов

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick --fix-missing  # Устанавливаем ImageMagick

      - name: Check ImageMagick version
        run: convert --version  # Проверяем, что ImageMagick установлен

      - name: Update ImageMagick policy
        run: |
          FILE="/etc/ImageMagick-6/policy.xml"
          if [ -f "$FILE" ]; then
            sudo sed -i.bak 's|<policy domain="path" rights="none" pattern="@/tmp/*" />|<policy domain="path" rights="read|write" pattern="@/tmp/*" />|' "$FILE"
          else
            echo '<policys>' | sudo tee "$FILE"
            echo '  <policy domain="path" rights="read|write" pattern="@/tmp/*" />' | sudo tee -a "$FILE"
            echo '</policys>' | sudo tee -a "$FILE"
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Устанавливаем нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Обновляем pip
          pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt

      - name: Run the bot
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}  # Используем секреты
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: python bot.py  # Запускаем бота
